### ISSUE TITLE
[QA] 장바구니 오류

### ISSUE THREAD

**Issue by Huni0819** [nhnacademy-be4-InkBridge/frontend#121]
![Image](https://github.com/nhnacademy-be4-InkBridge/frontend/assets/122001936/cdb7b92c-5f79-46e1-97fc-70ed43b90604)

### 발견 시간
2024-03-14 (목) 23:24

1. 장바구니에서 수량을 감소시켜도 가격이 증가합니다.
2. 상품 상세페이지에서 수량이 0개인 상태로 상품을 장바구니에 담으면 상품이 담깁니다.

**Comment by minm063** [comment]
수정했습니다 #132
