### ISSUE TITLE
로그아웃 시 에러 페이지 이동

### ISSUE THREAD

**Issue by Huni0819** [nhnacademy-be4-InkBridge/frontend#159]
![Image](https://github.com/nhnacademy-be4-InkBridge/frontend/assets/122001936/22acde55-0aae-4641-9094-008d9d0868b5)

 

![Image](https://github.com/nhnacademy-be4-InkBridge/frontend/assets/122001936/cdc8c10c-34b3-4626-8ff2-6fec6b8a34a1)

### 발견  시간
2024년 03월 22일 (금) 오후 08시 50분

### 발견 오류
로그아웃 시 404 에러 페이지로 이동합니다.

**Comment by minseo9974** [comment]
로컬이랑 배포환경 확인해보니까
에러페이지로 이동하는 에러가 발생하지 않네요.
무언가 다른 에러랑 겹쳤었나봐요
